### ISSUE TITLE
repeat

### ISSUE THREAD

**Issue by Mario-35** [udaysingh236/odata-sql-connect#2]
Hi

good job

I think a repeat line mistake in connector.ts line 255

**Comment by udaysingh236** [comment]
Hi there,

Thank you for checking the code, Could you please elaborate more on it? The issue that you saw and the steps to reproduce it.
However, if I check line #255 of connector.ts:

        } else if (this.dbType === DbTypes.MySql) {
            paramName = `${dbParamVals.mySql}${bindVarName}`;
        } else if (this.dbType === DbTypes.MsSql) {
            paramName = `${dbParamVals.msSql}${bindVarName}`;

Line 255 checks for My SQL type db and the other condition checks for Microsoft SQL server.

Thank you

**Comment by udaysingh236** [comment]
Closing this issue, as not much activity
